# Generated by Django 5.2.5 on 2025-08-31 10:48

import django.db.models.deletion
import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('customers', '0002_alter_customer_options_customer_allergies_and_more'),
        ('reservations', '0003_alter_reservation_table'),
    ]

    operations = [
        migrations.CreateModel(
            name='NotificationPreference',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('reservation_confirmations', models.BooleanField(default=True, verbose_name='Confirmaciones de reserva')),
                ('reservation_reminders', models.BooleanField(default=True, verbose_name='Recordatorios de reserva')),
                ('promotional_emails', models.BooleanField(default=True, verbose_name='Emails promocionales')),
                ('feedback_requests', models.BooleanField(default=True, verbose_name='Solicitudes de feedback')),
                ('email_enabled', models.BooleanField(default=True, verbose_name='Email habilitado')),
                ('sms_enabled', models.BooleanField(default=False, verbose_name='SMS habilitado')),
                ('push_enabled', models.BooleanField(default=True, verbose_name='Push habilitado')),
                ('quiet_hours_start', models.TimeField(blank=True, null=True, verbose_name='Inicio horas silencio')),
                ('quiet_hours_end', models.TimeField(blank=True, null=True, verbose_name='Fin horas silencio')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('customer', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='notification_preferences', to='customers.customer', verbose_name='Cliente')),
            ],
            options={
                'verbose_name': 'Preferencia de Notificación',
                'verbose_name_plural': 'Preferencias de Notificación',
            },
        ),
        migrations.CreateModel(
            name='NotificationTemplate',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, unique=True, verbose_name='Nombre')),
                ('type', models.CharField(choices=[('reservation_confirmation', 'Confirmación de Reserva'), ('reservation_reminder', 'Recordatorio de Reserva'), ('reservation_cancelled', 'Reserva Cancelada'), ('reservation_modified', 'Reserva Modificada'), ('customer_welcome', 'Bienvenida Cliente'), ('promotion', 'Promoción'), ('system_alert', 'Alerta del Sistema'), ('feedback_request', 'Solicitud de Feedback')], max_length=30, verbose_name='Tipo')),
                ('channel', models.CharField(choices=[('email', 'Email'), ('sms', 'SMS'), ('push', 'Push Notification'), ('in_app', 'Notificación In-App')], max_length=10, verbose_name='Canal')),
                ('subject_template', models.CharField(max_length=200, verbose_name='Template del asunto')),
                ('message_template', models.TextField(verbose_name='Template del mensaje')),
                ('html_template', models.TextField(blank=True, verbose_name='Template HTML')),
                ('is_active', models.BooleanField(default=True, verbose_name='Activo')),
                ('variables', models.JSONField(blank=True, default=list, help_text='Lista de variables que puede usar este template', verbose_name='Variables disponibles')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name': 'Template de Notificación',
                'verbose_name_plural': 'Templates de Notificación',
                'unique_together': {('type', 'channel')},
            },
        ),
        migrations.CreateModel(
            name='Notification',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('type', models.CharField(choices=[('reservation_confirmation', 'Confirmación de Reserva'), ('reservation_reminder', 'Recordatorio de Reserva'), ('reservation_cancelled', 'Reserva Cancelada'), ('reservation_modified', 'Reserva Modificada'), ('customer_welcome', 'Bienvenida Cliente'), ('promotion', 'Promoción'), ('system_alert', 'Alerta del Sistema'), ('feedback_request', 'Solicitud de Feedback')], max_length=30, verbose_name='Tipo')),
                ('channel', models.CharField(choices=[('email', 'Email'), ('sms', 'SMS'), ('push', 'Push Notification'), ('in_app', 'Notificación In-App')], max_length=10, verbose_name='Canal')),
                ('subject', models.CharField(max_length=200, verbose_name='Asunto')),
                ('message', models.TextField(verbose_name='Mensaje')),
                ('html_message', models.TextField(blank=True, verbose_name='Mensaje HTML')),
                ('priority', models.CharField(choices=[('low', 'Baja'), ('normal', 'Normal'), ('high', 'Alta'), ('urgent', 'Urgente')], default='normal', max_length=10, verbose_name='Prioridad')),
                ('status', models.CharField(choices=[('pending', 'Pendiente'), ('sent', 'Enviada'), ('delivered', 'Entregada'), ('failed', 'Fallida'), ('read', 'Leída')], default='pending', max_length=10, verbose_name='Estado')),
                ('metadata', models.JSONField(blank=True, default=dict, verbose_name='Metadatos')),
                ('scheduled_for', models.DateTimeField(blank=True, null=True, verbose_name='Programada para')),
                ('sent_at', models.DateTimeField(blank=True, null=True, verbose_name='Enviada en')),
                ('delivered_at', models.DateTimeField(blank=True, null=True, verbose_name='Entregada en')),
                ('read_at', models.DateTimeField(blank=True, null=True, verbose_name='Leída en')),
                ('error_message', models.TextField(blank=True, verbose_name='Mensaje de error')),
                ('retry_count', models.PositiveIntegerField(default=0, verbose_name='Intentos de reenvío')),
                ('max_retries', models.PositiveIntegerField(default=3, verbose_name='Máximo intentos')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('customer', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='notifications', to='customers.customer', verbose_name='Cliente')),
                ('reservation', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='notifications', to='reservations.reservation', verbose_name='Reserva')),
            ],
            options={
                'verbose_name': 'Notificación',
                'verbose_name_plural': 'Notificaciones',
                'ordering': ['-created_at'],
                'indexes': [models.Index(fields=['customer', 'status'], name='notificatio_custome_3c5f98_idx'), models.Index(fields=['type', 'channel'], name='notificatio_type_a10e92_idx'), models.Index(fields=['scheduled_for'], name='notificatio_schedul_cf7340_idx'), models.Index(fields=['created_at'], name='notificatio_created_46ad24_idx'), models.Index(fields=['reservation'], name='notificatio_reserva_9134a9_idx')],
            },
        ),
    ]
