# Generated by Django 5.2.5 on 2025-08-31 10:48

import customers.models
import django.core.validators
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('customers', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='customer',
            options={'verbose_name': 'Cliente', 'verbose_name_plural': 'Clientes'},
        ),
        migrations.AddField(
            model_name='customer',
            name='allergies',
            field=models.TextField(blank=True, verbose_name='Alergias'),
        ),
        migrations.AddField(
            model_name='customer',
            name='birth_date',
            field=models.DateField(blank=True, null=True, verbose_name='Fecha de nacimiento'),
        ),
        migrations.AddField(
            model_name='customer',
            name='customer_score',
            field=models.PositiveIntegerField(default=100, verbose_name='Puntuación cliente'),
        ),
        migrations.AddField(
            model_name='customer',
            name='no_show_count',
            field=models.PositiveIntegerField(default=0, verbose_name='No asistencias'),
        ),
        migrations.AddField(
            model_name='customer',
            name='preferences',
            field=models.TextField(blank=True, verbose_name='Preferencias'),
        ),
        migrations.AlterField(
            model_name='customer',
            name='cancelled_reservations',
            field=models.PositiveIntegerField(default=0, verbose_name='Reservas canceladas'),
        ),
        migrations.AlterField(
            model_name='customer',
            name='first_name',
            field=models.CharField(max_length=100, validators=[django.core.validators.RegexValidator('^[a-zA-ZáéíóúÁÉÍÓÚñÑ\\s]+$', 'Solo letras y espacios permitidos')], verbose_name='Nombre'),
        ),
        migrations.AlterField(
            model_name='customer',
            name='is_active',
            field=models.BooleanField(default=True, verbose_name='Activo'),
        ),
        migrations.AlterField(
            model_name='customer',
            name='last_name',
            field=models.CharField(max_length=100, validators=[django.core.validators.RegexValidator('^[a-zA-ZáéíóúÁÉÍÓÚñÑ\\s]+$', 'Solo letras y espacios permitidos')], verbose_name='Apellido'),
        ),
        migrations.AlterField(
            model_name='customer',
            name='phone',
            field=models.CharField(max_length=20, validators=[customers.models.validate_phone_number], verbose_name='Teléfono'),
        ),
        migrations.AlterField(
            model_name='customer',
            name='total_reservations',
            field=models.PositiveIntegerField(default=0, verbose_name='Total reservas'),
        ),
        migrations.AddIndex(
            model_name='customer',
            index=models.Index(fields=['email'], name='customers_c_email_4fdeb3_idx'),
        ),
        migrations.AddIndex(
            model_name='customer',
            index=models.Index(fields=['phone'], name='customers_c_phone_8493fa_idx'),
        ),
        migrations.AddIndex(
            model_name='customer',
            index=models.Index(fields=['customer_score'], name='customers_c_custome_0da4e5_idx'),
        ),
        migrations.AddIndex(
            model_name='customer',
            index=models.Index(fields=['is_active', 'created_at'], name='customers_c_is_acti_3160aa_idx'),
        ),
    ]
