services:
  db:
    image: postgres:15
    environment:
      POSTGRES_DB: restaurant_reservations
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
    ports:
      - "5434:5432"
    volumes:
      - postgres_data:/var/lib/postgresql/data

  redis:
    image: redis:7-alpine
    ports:
      - "6381:6379"

  web:
    build: .
    ports:
      - "8000:8000"
    volumes:
      - .:/app
    depends_on:
      - db
      - redis
    environment:
      - DATABASE_URL=postgres://postgres:postgres@db:5432/restaurant_reservations
      - REDIS_URL=redis://redis:6379/0
      - EMAIL_BACKEND=django.core.mail.backends.console.EmailBackend
      - DEFAULT_FROM_EMAIL=ReservaFlow <noreply@reservaflow.com>
      - RESERVATION_PENDING_TIMEOUT=15
    command: >
      sh -c "uv run python manage.py migrate &&
             uv run python manage.py runserver 0.0.0.0:8000"

  celery:
    build: .
    volumes:
      - .:/app
    depends_on:
      - db
      - redis
    environment:
      - DATABASE_URL=postgres://postgres:postgres@db:5432/restaurant_reservations
      - REDIS_URL=redis://redis:6379/0
      - EMAIL_BACKEND=django.core.mail.backends.console.EmailBackend
      - DEFAULT_FROM_EMAIL=ReservaFlow <noreply@reservaflow.com>
      - RESERVATION_PENDING_TIMEOUT=15
    command: uv run celery -A config worker --loglevel=info

  celery-beat:
    build: .
    volumes:
      - .:/app
    depends_on:
      - db
      - redis
    environment:
      - DATABASE_URL=postgres://postgres:postgres@db:5432/restaurant_reservations
      - REDIS_URL=redis://redis:6379/0
      - EMAIL_BACKEND=django.core.mail.backends.console.EmailBackend
      - DEFAULT_FROM_EMAIL=ReservaFlow <noreply@reservaflow.com>
      - RESERVATION_PENDING_TIMEOUT=15
    command: uv run celery -A config beat --loglevel=info

volumes:
  postgres_data:
